# Generated by Django 3.2.6 on 2022-06-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
