# Generated by Django 3.2.6 on 2022-06-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_slot_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
