# Generated by Django 3.2.6 on 2022-06-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_slot_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='description',
        ),
    ]
