# Generated by Django 3.2.6 on 2022-07-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_slot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
